ARG BASE_IMAGE=nvidia/cudagl:11.3.0-devel-ubuntu20.04
FROM $BASE_IMAGE

# Install tzdata
RUN apt-get update
RUN	apt-get -y upgrade 
RUN DEBIAN_FRONTEND=noninteractive TZ=Europe apt-get -y install tzdata

RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	sudo \
	libglu1-mesa-dev \
	xdg-user-dirs \
	pulseaudio \
	x11-xserver-utils \
	libsdl2-2.0-0 \
	libsdl2-dev

# Install Python packages
RUN pip install numpy \
	pip install msgpack-rpc-python

RUN python3 -m pip install --upgrade pip && \
    pip3 install setuptools wheel && \
    pip3 install airsim
	
RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash airsim_user && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
	adduser airsim_user sudo && \
	adduser airsim_user audio && \
	adduser airsim_user video

USER airsim_user
WORKDIR /home/airsim_user

RUN mkdir -p /home/airsim_user/Documents/AirSim
COPY settings.json /home/airsim_user/Documents/AirSim
#ADD Documents /home/airsim_user/Documents

RUN sudo chown -R airsim_user /home/airsim_user
